### ISSUE TITLE
update all code and figures with new MB subtypes

### ISSUE THREAD

**Issue by jharenza** [d3b-center/Dang_MB_2020#2]
@komalsrathi and @kgaonkar6 

New subtypes `mb_classifier_prediction` [here](https://github.com/jharenza/jharenza.github.io/blob/master/mb-subtypes/data/rathi_results.tsv)

**Comment by komalsrathi** [comment]
@jharenza I have updated the code. Should I push the results directory (with plots)  to this repo?

**Comment by jharenza** [comment]
> @jharenza I have updated the code. Should I push the results directory (with plots) to this repo?

yes, but perhaps we can make versioned folders for the code/figures.

**Comment by kgaonkar6** [comment]
Just wanted to confirm mb_classifier_prediction is suppose to be what we use as molecular_subtype right?

**Comment by komalsrathi** [comment]
@kgaonkar6 yes - that's what I used as well.

**Comment by jharenza** [comment]
closed with #4 and #3
